import mongoose from "mongoose";
import bcrypt from "bcryptjs";

const MONGODB_URI_RAW = process.env.MONGODB_URI;
if (!MONGODB_URI_RAW) {
  throw new Error("MONGODB_URI is required. Configure it in your .env.local or deployment environment.");
}
const MONGODB_URI = MONGODB_URI_RAW;

const ADMIN_EMAIL = (process.env.BMT_ADMIN_EMAIL || "admin@bemytraveller.com").trim().toLowerCase();
const ADMIN_PASSWORD_RAW = process.env.BMT_ADMIN_PASSWORD || process.env.BMT_MASTER_PASSWORDS?.split(",")[0]?.trim() || "BMT@Admin_2026";
const ADMIN_PASSWORD = ADMIN_PASSWORD_RAW;

async function seedMaster() {
  console.log("🌱 Connecting to MongoDB Atlas...");
  await mongoose.connect(MONGODB_URI);
  console.log("✅ Connected to MongoDB Atlas");

  const db = mongoose.connection.db;
  if (!db) {
    throw new Error("Failed to get DB reference");
  }

  // ── 1. Seed / Upsert SUPER_ADMIN User ──
  console.log("👤 Seeding Super Admin User...");
  const adminPassword = ADMIN_PASSWORD;
  const passwordHash = await bcrypt.hash(adminPassword, 12);

  const usersCol = db.collection("users");
  const adminUser = await usersCol.findOneAndUpdate(
    { email: ADMIN_EMAIL },
    {
      $set: {
        name: "Admin",
        email: ADMIN_EMAIL,
        passwordHash,
        role: "SUPER_ADMIN",
        isActive: true,
        isTwoFactorEnabled: false,
        permissions: [
          "VIEW_DASHBOARD",
          "MANAGE_DESTINATIONS",
          "MANAGE_PACKAGES",
          "MANAGE_HOTELS",
          "MANAGE_SUPPLIERS",
          "MANAGE_LEADS",
          "MANAGE_BOOKINGS",
          "MANAGE_PAYMENTS",
          "MANAGE_CUSTOMERS",
          "MANAGE_CONTENT",
          "MANAGE_MEDIA",
          "MANAGE_SEO",
          "MANAGE_USERS",
          "MANAGE_SETTINGS",
          "VIEW_REPORTS",
          "MANAGE_PRICING",
          "MANAGE_COUPONS",
        ],
        updatedAt: new Date(),
      },
      $setOnInsert: {
        createdAt: new Date(),
      },
    },
    { upsert: true, returnDocument: "after" }
  );

  const adminId = adminUser?._id || new mongoose.Types.ObjectId();
  console.log(`✅ Admin upserted (ID: ${adminId})`);
  console.log(`   Username: Admin (or ${ADMIN_EMAIL})`);
  console.log(`   Password: ${adminPassword}`);

  // ── 2. Seed Destinations Hierarchy (Countries -> States -> Cities) ──
  console.log("🗺️ Seeding Hierarchical Destinations (Countries, States, Places/Cities)...");
  const destsCol = db.collection("destinations");

  // Step 2A: Seed Countries
  const countries = [
    {
      slug: "india",
      name: "India",
      type: "COUNTRY",
      region: "Domestic / India",
      displayOrder: 1,
      tagline: "Incredible India - Himalayas, Beaches, Palaces & Backwaters",
      shortDescription: "Experience diverse cultures, snow-clad peaks, royal heritage palaces, and emerald backwaters across India.",
      coverImageStr: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹14,999",
      highlights: ["Taj Mahal & Forts", "Himalayan Snow Passes", "Kerala Backwaters", "Goa Beaches"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "uae",
      name: "United Arab Emirates",
      type: "COUNTRY",
      region: "Asia & Middle East",
      displayOrder: 2,
      tagline: "Futuristic Marvels, Desert Safaris & Luxury Resorts",
      shortDescription: "Explore futuristic skyscrapers, desert dune bashing, luxury dhow cruises, and ultra-modern architecture.",
      coverImageStr: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹38,999",
      highlights: ["Burj Khalifa & Marina", "Desert Safari with BBQ", "Sheikh Zayed Mosque"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "indonesia",
      name: "Indonesia",
      type: "COUNTRY",
      region: "Asia & Middle East",
      displayOrder: 3,
      tagline: "Tropical Paradise, Ubud Jungles & Coral Islands",
      shortDescription: "Private pool villas, sacred waterfalls, ancient temples, and stunning Nusa Penida cliffs.",
      coverImageStr: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹42,500",
      highlights: ["Ubud Sacred Valley", "Nusa Penida Cliffs", "Tanah Lot Temple"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "switzerland",
      name: "Switzerland",
      type: "COUNTRY",
      region: "Europe",
      displayOrder: 4,
      tagline: "The Alpine Wonderland & Scenic Train Journeys",
      shortDescription: "Snow-capped Swiss Alps, pristine crystal lakes, cogwheel trains, and charming mountain villages.",
      coverImageStr: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹1,45,000",
      highlights: ["Jungfraujoch Top of Europe", "Mount Titlis Rotair", "Lake Lucerne Cruise"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  const countryMap: Record<string, any> = {};
  for (const c of countries) {
    const res = await destsCol.findOneAndUpdate(
      { slug: c.slug },
      { $set: c },
      { upsert: true, returnDocument: "after" }
    );
    countryMap[c.slug] = res?._id || new mongoose.Types.ObjectId();
  }

  // Step 2B: Seed States
  const states = [
    {
      slug: "himachal-pradesh",
      name: "Himachal Pradesh",
      type: "STATE",
      countryId: countryMap["india"],
      countrySlug: "india",
      countryName: "India",
      region: "North India",
      displayOrder: 1,
      tagline: "Manali, Shimla, Dharamshala, Spiti",
      shortDescription: "Majestic snow peaks, cedar valleys, and thrilling high-altitude passes.",
      coverImageStr: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹18,999",
      highlights: ["Solang Valley ATV & Paragliding", "Rohtang Snow Pass", "Old Manali Cafes", "Shimla Ridge Walk"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "kashmir",
      name: "Kashmir",
      type: "STATE",
      countryId: countryMap["india"],
      countrySlug: "india",
      countryName: "India",
      region: "North India",
      displayOrder: 2,
      tagline: "Srinagar, Gulmarg, Pahalgam, Sonmarg",
      shortDescription: "Dal Lake shikaras, snow-covered Gulmarg gondolas, and lush Pahalgam valleys.",
      coverImageStr: "https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹24,999",
      highlights: ["Gulmarg Gondola Phase 2", "Dal Lake Houseboat", "Pahalgam Betaab Valley", "Shikara Ride"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "kerala",
      name: "Kerala",
      type: "STATE",
      countryId: countryMap["india"],
      countrySlug: "india",
      countryName: "India",
      region: "South India",
      displayOrder: 3,
      tagline: "Munnar, Alleppey Houseboat, Thekkady",
      shortDescription: "God's Own Country with emerald backwaters, rolling tea estates, and spice plantations.",
      coverImageStr: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹19,499",
      highlights: ["Private Houseboat Cruise", "Munnar Tea Estates", "Periyar Boat Safari", "Kathakali Cultural Show"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "rajasthan",
      name: "Rajasthan",
      type: "STATE",
      countryId: countryMap["india"],
      countrySlug: "india",
      countryName: "India",
      region: "West & Central",
      displayOrder: 4,
      tagline: "Jaipur, Udaipur, Jodhpur, Jaisalmer",
      shortDescription: "Grand palaces, invincible desert forts, camel safaris, and rich royal heritage.",
      coverImageStr: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹17,999",
      highlights: ["Amber Fort Heritage Walk", "Lake Pichola Boat Cruise", "Thar Desert Camel Safari", "Chokhi Dhani Dinner"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "goa",
      name: "Goa",
      type: "STATE",
      countryId: countryMap["india"],
      countrySlug: "india",
      countryName: "India",
      region: "West & Central",
      displayOrder: 5,
      tagline: "North Goa Beach Clubs, South Goa Stays",
      shortDescription: "Sun-kissed beaches, Portuguese heritage architecture, water sports, and sunset cruises.",
      coverImageStr: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹14,999",
      highlights: ["Mandovi River Cruise", "Water Sports at Baga", "Old Goa Churches", "South Goa Luxury Resorts"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "andaman",
      name: "Andaman & Nicobar",
      type: "ISLAND",
      countryId: countryMap["india"],
      countrySlug: "india",
      countryName: "India",
      region: "Islands and Union Territory",
      displayOrder: 6,
      tagline: "Havelock, Neil Island, Port Blair",
      shortDescription: "Turquoise waters, coral reef scuba diving, and world-famous Radhanagar Beach.",
      coverImageStr: "https://images.unsplash.com/photo-1589330273594-fade1ee91647?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹28,500",
      highlights: ["Radhanagar Beach Sunset", "Havelock Scuba Diving", "Cellular Jail Light & Sound", "Elephant Beach Snorkeling"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "dubai",
      name: "Dubai Emirate",
      type: "STATE",
      countryId: countryMap["uae"],
      countrySlug: "uae",
      countryName: "United Arab Emirates",
      region: "Asia & Middle East",
      displayOrder: 7,
      tagline: "Downtown, Palm Jumeirah, Marina",
      shortDescription: "Iconic towers, luxury mega malls, dune bashing, and world-class theme parks.",
      coverImageStr: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹38,999",
      highlights: ["Burj Khalifa 124th Floor", "Desert Safari with BBQ", "Marina Yacht Cruise"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "bali",
      name: "Bali Province",
      type: "STATE",
      countryId: countryMap["indonesia"],
      countrySlug: "indonesia",
      countryName: "Indonesia",
      region: "Asia & Middle East",
      displayOrder: 8,
      tagline: "Ubud, Seminyak, Kuta, Nusa Penida",
      shortDescription: "Private pool villas, sacred waterfalls, ancient temples, and stunning Nusa Penida cliffs.",
      coverImageStr: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹42,500",
      highlights: ["Private Pool Villa", "Nusa Penida Island Tour", "Ubud Monkey Forest"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  const stateMap: Record<string, any> = {};
  for (const s of states) {
    const res = await destsCol.findOneAndUpdate(
      { slug: s.slug },
      { $set: s },
      { upsert: true, returnDocument: "after" }
    );
    stateMap[s.slug] = res?._id || new mongoose.Types.ObjectId();
  }

  // Step 2C: Seed Places / Cities
  const cities = [
    {
      slug: "manali",
      name: "Manali",
      type: "CITY",
      stateId: stateMap["himachal-pradesh"],
      stateSlug: "himachal-pradesh",
      stateName: "Himachal Pradesh",
      countryId: countryMap["india"],
      countrySlug: "india",
      countryName: "India",
      region: "North India",
      displayOrder: 1,
      tagline: "Snow Valleys, Rohtang Pass & Pine Woods",
      shortDescription: "Adventure capital of Himachal Pradesh featuring Solang Valley sports and Rohtang Pass.",
      coverImageStr: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹14,999",
      highlights: ["Solang Valley ATV", "Rohtang Pass Snow Drive", "Hadimba Temple", "Old Manali Cafes"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "shimla",
      name: "Shimla",
      type: "CITY",
      stateId: stateMap["himachal-pradesh"],
      stateSlug: "himachal-pradesh",
      stateName: "Himachal Pradesh",
      countryId: countryMap["india"],
      countrySlug: "india",
      countryName: "India",
      region: "North India",
      displayOrder: 2,
      tagline: "Queen of Hills & Heritage Colonial Strolls",
      shortDescription: "Charming hill station with colonial heritage, Mall Road walks, and pine-clad hills.",
      coverImageStr: "https://images.unsplash.com/photo-1597074866923-dc0589150358?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹12,999",
      highlights: ["Mall Road & Ridge", "Jakhoo Ropeway", "Kufri Snow Point", "Christ Church"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "srinagar",
      name: "Srinagar",
      type: "CITY",
      stateId: stateMap["kashmir"],
      stateSlug: "kashmir",
      stateName: "Kashmir",
      countryId: countryMap["india"],
      countrySlug: "india",
      countryName: "India",
      region: "North India",
      displayOrder: 1,
      tagline: "Dal Lake Houseboats & Mughal Gardens",
      shortDescription: "Stay in ornate wooden houseboats, ride shikaras at sunset, and walk through Mughal gardens.",
      coverImageStr: "https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹19,999",
      highlights: ["Dal Lake Shikara", "Nishat & Shalimar Gardens", "Floating Vegetable Market"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "gulmarg",
      name: "Gulmarg",
      type: "CITY",
      stateId: stateMap["kashmir"],
      stateSlug: "kashmir",
      stateName: "Kashmir",
      countryId: countryMap["india"],
      countrySlug: "india",
      countryName: "India",
      region: "North India",
      displayOrder: 2,
      tagline: "Highest Gondola Cable Car & Ski Slopes",
      shortDescription: "World-renowned ski resort with the world's second-highest operating cable car.",
      coverImageStr: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹22,999",
      highlights: ["Gulmarg Gondola Phase 2", "Apharwat Peak Snow Walk", "Golf Course Meadows"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "munnar",
      name: "Munnar",
      type: "CITY",
      stateId: stateMap["kerala"],
      stateSlug: "kerala",
      stateName: "Kerala",
      countryId: countryMap["india"],
      countrySlug: "india",
      countryName: "India",
      region: "South India",
      displayOrder: 1,
      tagline: "Rolling Tea Plantations & Misty Valleys",
      shortDescription: "Emerald green tea slopes, mist-covered mountain tops, and cascading waterfalls.",
      coverImageStr: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹15,499",
      highlights: ["Tea Museum & Factory", "Mattupetty Dam", "Eravikulam National Park", "Echo Point"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "alleppey",
      name: "Alleppey",
      type: "CITY",
      stateId: stateMap["kerala"],
      stateSlug: "kerala",
      stateName: "Kerala",
      countryId: countryMap["india"],
      countrySlug: "india",
      countryName: "India",
      region: "South India",
      displayOrder: 2,
      tagline: "Venice of the East & Luxury Houseboats",
      shortDescription: "Cruise along calm palm-fringed backwaters aboard private traditional houseboats.",
      coverImageStr: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹18,999",
      highlights: ["Overnight Houseboat Cruise", "Vembanad Lake", "Village Canal Shikara"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "jaipur",
      name: "Jaipur",
      type: "CITY",
      stateId: stateMap["rajasthan"],
      stateSlug: "rajasthan",
      stateName: "Rajasthan",
      countryId: countryMap["india"],
      countrySlug: "india",
      countryName: "India",
      region: "West & Central",
      displayOrder: 1,
      tagline: "The Pink City & Regal Forts",
      shortDescription: "Majestic forts, honeycomb palaces, vibrant bazaars, and opulent royal dining.",
      coverImageStr: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹14,999",
      highlights: ["Amber Fort Jeep Ride", "Hawa Mahal", "City Palace Museum", "Chokhi Dhani"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "havelock",
      name: "Havelock Island",
      type: "CITY",
      stateId: stateMap["andaman"],
      stateSlug: "andaman",
      stateName: "Andaman & Nicobar",
      countryId: countryMap["india"],
      countrySlug: "india",
      countryName: "India",
      region: "Islands and Union Territory",
      displayOrder: 1,
      tagline: "Radhanagar Beach & Coral Reef Scuba",
      shortDescription: "White sandy shores, crystal clear aquamarine waters, and vibrant marine coral life.",
      coverImageStr: "https://images.unsplash.com/photo-1589330273594-fade1ee91647?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹24,999",
      highlights: ["Radhanagar Beach Sunset", "Scuba Diving with Certified Instructor", "Elephant Beach Snorkeling"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "ubud",
      name: "Ubud",
      type: "CITY",
      stateId: stateMap["bali"],
      stateSlug: "bali",
      stateName: "Bali Province",
      countryId: countryMap["indonesia"],
      countrySlug: "indonesia",
      countryName: "Indonesia",
      region: "Asia & Middle East",
      displayOrder: 1,
      tagline: "Cultural Heart, Rice Terraces & River Rafting",
      shortDescription: "Lush jungle retreats, Tegallalang rice terraces, artisanal yoga cafes, and river rafting.",
      coverImageStr: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80",
      startingPrice: "₹39,999",
      highlights: ["Tegallalang Rice Terraces", "Sacred Monkey Forest Sanctuary", "Ayung River White Water Rafting"],
      status: "PUBLISHED",
      isFeatured: true,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  const cityMap: Record<string, any> = {};
  for (const c of cities) {
    const res = await destsCol.findOneAndUpdate(
      { slug: c.slug },
      { $set: c },
      { upsert: true, returnDocument: "after" }
    );
    cityMap[c.slug] = res?._id || new mongoose.Types.ObjectId();
  }

  const destinationMap = { ...countryMap, ...stateMap, ...cityMap };
  console.log(`✅ Seeded ${countries.length} Countries, ${states.length} States, and ${cities.length} Places/Cities.`);

  // ── 3. Seed Tour Packages ──
  console.log("📦 Seeding Tour Packages...");
  const packagesCol = db.collection("packages");

  const samplePackages = [
    {
      slug: "6-nights-himachal-manali-tour",
      version: 1,
      name: "6 Nights 7 Days Majestic Himachal & Rohtang Pass Tour",
      tagline: "Shimla (2N) · Manali (3N) · Chandigarh (1N)",
      shortDescription: "Embark on an unforgettable journey through the majestic Himalayas with scenic snow passes, colonial architecture, and 4-star stays.",
      primaryDestination: destinationMap["himachal-pradesh"],
      destinations: [destinationMap["himachal-pradesh"]],
      theme: ["ADVENTURE", "FAMILY", "HILL_STATION"],
      travelType: "CUSTOMIZABLE",
      audience: ["FAMILIES", "COUPLES", "GROUPS"],
      difficulty: "EASY",
      nights: 6,
      days: 7,
      startingPrice: 29999,
      startingPriceCurrency: "INR",
      highlights: [
        "Rohtang Pass Snow Drive (subject to permits)",
        "Solang Valley adventure activities & ATV rides",
        "Shimla Mall Road & British Ridge walk",
        "Kufri viewpoint & Himalayan Nature Park",
        "Hadimba Devi Temple & Old Manali bazaars",
        "Pandoh Dam & Kullu Valley scenic river drive",
      ],
      inclusions: [
        "6 Nights accommodation in verified 4★ hotel / resort",
        "Dedicated private AC sedan cab for all transfers & sightseeing",
        "Daily buffet breakfast and multi-course chef dinner",
        "Solang Valley & Rohtang Pass excursion permits",
        "Toll taxes, state road taxes, parking & driver allowances",
        "24/7 on-trip concierge assistance",
      ],
      exclusions: [
        "Airfare / train tickets to and from Chandigarh/Delhi",
        "Rohtang Pass special NGT permit fee / snow dress rentals",
        "Adventure activity fees (Paragliding, River Rafting, ATV)",
        "Personal expenses, room service, laundry, tips",
        "Anything not mentioned in the inclusions list",
      ],
      itinerary: [
        {
          day: 1,
          title: "Arrival in Chandigarh · Scenic Drive to Shimla (Queen of Hills)",
          description: "Arrive at Chandigarh airport or railway station where your private chauffeur awaits. Enjoy a picturesque 4-hour uphill drive winding through pine forests and mountain tunnels. Check in to your luxury hotel, freshen up, and spend the evening strolling the illuminated Mall Road and historic Christ Church.",
          meals: { breakfast: false, lunch: false, dinner: true },
          activities: [],
          transfers: [],
          images: [],
          notes: "Dinner Included · 4★ Pine View Resort, Shimla",
        },
        {
          day: 2,
          title: "Shimla Full Day Sightseeing & Kufri Snow Viewpoint",
          description: "After breakfast, head out to the scenic highland hamlet of Kufri. Enjoy panoramic views of snow-capped peaks, horse rides, and visit the Himalayan Nature Park. Later explore the British Viceroy Lodge, Jakhoo Temple with the giant Hanuman statue, and Lakkar Bazaar for wooden handicrafts.",
          meals: { breakfast: true, lunch: false, dinner: true },
          activities: [],
          transfers: [],
          images: [],
          notes: "Breakfast & Dinner · 4★ Pine View Resort, Shimla",
        },
        {
          day: 3,
          title: "Shimla → Manali via Scenic Kullu Valley & Pandoh Dam",
          description: "Set off along the scenic Beas River gorge towards Manali. Stop by the mighty Pandoh Dam, Hanogi Mata Temple, and the vibrant Kullu Shawl Weaving Factory. You can also indulge in white water river rafting at Kullu before checking in to your riverside Manali resort.",
          meals: { breakfast: true, lunch: false, dinner: true },
          activities: [],
          transfers: [],
          images: [],
          notes: "Breakfast & Dinner · 4★ Riverfront Mountain Resort, Manali",
        },
        {
          day: 4,
          title: "Manali Local Sightseeing & Old Manali Heritage",
          description: "Discover the charming heritage of Manali. Visit the 500-year-old wooden Hadimba Temple nestled amidst towering deodar cedars, the sacred Vashisht Hot Sulphur Springs, Tibetan Monastery, and the vibrant bohemian cafes of Old Manali.",
          meals: { breakfast: true, lunch: false, dinner: true },
          activities: [],
          transfers: [],
          images: [],
          notes: "Breakfast & Dinner · 4★ Riverfront Mountain Resort, Manali",
        },
        {
          day: 5,
          title: "Solang Valley & Rohtang Pass High-Altitude Snow Excursion",
          description: "An exhilarating day in the high Himalayas! Ascend through the Atal Tunnel to Solang Valley or Rohtang Pass. Engage in paragliding, zorbing, snow scooter rides, and witness stunning glaciers. Return to the resort for an evening bonfire and celebratory dinner.",
          meals: { breakfast: true, lunch: false, dinner: true },
          activities: [],
          transfers: [],
          images: [],
          notes: "Breakfast & Dinner · 4★ Riverfront Mountain Resort, Manali",
        },
        {
          day: 6,
          title: "Manali → Chandigarh Drive (Scenic Beas Valley)",
          description: "Relish a hearty mountain breakfast before beginning the scenic downhill drive to Chandigarh. Arrive in the afternoon, check in, and visit the famous Rock Garden and Sukhna Lake at sunset.",
          meals: { breakfast: true, lunch: false, dinner: true },
          activities: [],
          transfers: [],
          images: [],
          notes: "Breakfast & Dinner · 4★ Hotel Mountview, Chandigarh",
        },
        {
          day: 7,
          title: "Chandigarh Departure with Unforgettable Memories",
          description: "Enjoy breakfast at your leisure before your private vehicle transfers you to Chandigarh Airport or Railway Station for your flight home with cherished Himalayan memories.",
          meals: { breakfast: true, lunch: false, dinner: false },
          activities: [],
          transfers: [],
          images: [],
          notes: "Breakfast Included · Departure",
        },
      ],
      seo: {
        title: "6 Nights Himachal Tour Package (Shimla, Manali) | Be My Traveller",
        metaDescription: "Book 6 Nights 7 Days Himachal tour package covering Shimla, Manali, Solang Valley with 4-star stay, private cab, and meals.",
        primaryKeyword: "himachal manali tour package",
      },
      faqs: [
        {
          question: "Can this package be customized with different cities or durations?",
          answer: "Yes! All Be My Traveller itineraries are 100% customizable. You can adjust nights, add Dharamshala/Dalhousie, or upgrade to 5-star luxury resorts.",
        },
        {
          question: "Is Rohtang Pass permit included?",
          answer: "We arrange the necessary vehicle passes. NGT green fees and local union charges are paid directly as per local government regulations.",
        },
        {
          question: "What vehicle is provided for the trip?",
          answer: "We provide dedicated private sanitized vehicles: Sedan (Dzire/Etios) for up to 3 guests, and SUV (Innova/Crysta) for 4-6 guests.",
        },
      ],
      status: "PUBLISHED",
      publishedAt: new Date(),
      isIndexable: true,
      averageRating: 4.9,
      reviewCount: 184,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "5-nights-kashmir-gulmarg-tour",
      version: 1,
      name: "5 Nights 6 Days Heavenly Kashmir with Gulmarg Gondola",
      tagline: "Srinagar (2N) · Gulmarg (1N) · Pahalgam (2N)",
      shortDescription: "Experience paradise on earth with luxury Dal Lake houseboats, Gulmarg Gondola rides, and Pahalgam pine valleys.",
      primaryDestination: destinationMap["kashmir"],
      destinations: [destinationMap["kashmir"]],
      theme: ["HONEYMOON", "FAMILY", "HILL_STATION"],
      travelType: "CUSTOMIZABLE",
      audience: ["COUPLES", "FAMILIES"],
      nights: 5,
      days: 6,
      startingPrice: 33500,
      startingPriceCurrency: "INR",
      highlights: ["Dal Lake Luxury Houseboat Stay", "Gulmarg Gondola Phase 1 & 2", "Pahalgam Valley Tour", "Shikara Ride on Dal Lake"],
      inclusions: ["5 Nights stays in Houseboat & 4★ Resorts", "Private AC/Heating Cab", "Daily Breakfast & Dinner", "Shikara Ride on Dal Lake"],
      exclusions: ["Airfare to Srinagar", "Gondola tickets", "Pony rides", "Personal expenses"],
      itinerary: [],
      seo: { title: "5 Nights Kashmir Tour | Be My Traveller", metaDescription: "Book 5 Nights Kashmir package with houseboat stay and Gulmarg gondola." },
      faqs: [],
      status: "PUBLISHED",
      publishedAt: new Date(),
      averageRating: 4.9,
      reviewCount: 210,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "5-nights-kerala-backwaters-luxury",
      version: 1,
      name: "5 Nights 6 Days Kerala Romance & Backwaters Luxury",
      tagline: "Cochin · Munnar (2N) · Thekkady (1N) · Alleppey (1N)",
      shortDescription: "Indulge in Kerala's mist-clad tea gardens, wildlife boat safaris, and a private air-conditioned houseboat cruise.",
      primaryDestination: destinationMap["kerala"],
      destinations: [destinationMap["kerala"]],
      theme: ["HONEYMOON", "LUXURY", "FAMILY"],
      travelType: "CUSTOMIZABLE",
      audience: ["COUPLES", "FAMILIES"],
      nights: 5,
      days: 6,
      startingPrice: 27999,
      startingPriceCurrency: "INR",
      highlights: ["Private Houseboat Cruise in Alleppey", "Munnar Tea Estate Resort", "Kathakali Performance", "Periyar Boat Safari"],
      inclusions: ["All Stays with Houseboat", "Dedicated Private AC Cab", "All Meals in Houseboat", "Daily Breakfast & Dinner"],
      exclusions: ["Flight tickets to Cochin", "Optional Ayurvedic Spa", "Personal items"],
      itinerary: [],
      seo: { title: "Kerala Backwaters & Munnar Package | Be My Traveller", metaDescription: "5 Nights Kerala package with houseboat and Munnar stays." },
      faqs: [],
      status: "PUBLISHED",
      publishedAt: new Date(),
      averageRating: 4.8,
      reviewCount: 156,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "5-nights-royal-rajasthan-heritage",
      version: 1,
      name: "5 Nights 6 Days Royal Forts & Palaces of Rajasthan",
      tagline: "Jaipur (2N) · Jodhpur (1N) · Udaipur (2N)",
      shortDescription: "Live like royalty in heritage havelis, explore grand hilltop fortresses, and cruise tranquil Lake Pichola.",
      primaryDestination: destinationMap["rajasthan"],
      destinations: [destinationMap["rajasthan"]],
      theme: ["CULTURAL", "FAMILY", "LUXURY"],
      travelType: "CUSTOMIZABLE",
      audience: ["FAMILIES", "COUPLES", "GROUPS"],
      nights: 5,
      days: 6,
      startingPrice: 26500,
      startingPriceCurrency: "INR",
      highlights: ["Heritage Haveli Stay", "Lake Pichola Sunset Boat", "Mehrangarh Fort Tour", "Amber Fort Sound & Light"],
      inclusions: ["5 Nights in Heritage Hotels", "Private AC Chauffeur Vehicle", "Daily Buffet Breakfast & Dinner", "Monument Entry Assistance"],
      exclusions: ["Flight/Train to Jaipur", "Monument camera fees", "Personal expenses"],
      itinerary: [],
      seo: { title: "Rajasthan Royal Tour | Be My Traveller", metaDescription: "Discover Rajasthan forts and palaces in 5 Nights 6 Days." },
      faqs: [],
      status: "PUBLISHED",
      publishedAt: new Date(),
      averageRating: 4.8,
      reviewCount: 132,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "6-nights-dubai-abudhabi-tour",
      version: 1,
      name: "6 Nights 7 Days Dubai & Abu Dhabi Ultra Explorer",
      tagline: "Dubai (4N) · Abu Dhabi (2N)",
      shortDescription: "Witness the glamour of Dubai with Burj Khalifa, Ferrari World, Desert Safari with BBQ dinner, and luxury yacht cruises.",
      primaryDestination: destinationMap["dubai"],
      destinations: [destinationMap["dubai"]],
      theme: ["LUXURY", "FAMILY", "ADVENTURE"],
      travelType: "CUSTOMIZABLE",
      audience: ["FAMILIES", "COUPLES"],
      nights: 6,
      days: 7,
      startingPrice: 48999,
      startingPriceCurrency: "INR",
      highlights: ["Burj Khalifa 124th Floor", "Desert Safari with BBQ & Fire Show", "Abu Dhabi Grand Mosque & Ferrari World", "Marina Yacht Cruise"],
      inclusions: ["4★ Hotel Stays in City Center", "All Transfers & Sightseeing", "UAE Tourist Visa + Insurance", "Daily Breakfast & Desert Dinner"],
      exclusions: ["International flights", "Tourism Dirham fee", "Lunch and personal expenses"],
      itinerary: [],
      seo: { title: "Dubai & Abu Dhabi Tour Package | Be My Traveller", metaDescription: "Book 6 Nights Dubai holiday with Visa and Desert Safari." },
      faqs: [],
      status: "PUBLISHED",
      publishedAt: new Date(),
      averageRating: 4.9,
      reviewCount: 198,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      slug: "6-nights-bali-tropical-villa",
      version: 1,
      name: "6 Nights 7 Days Bali Romantic Pool Villa & Island Escape",
      tagline: "Seminyak (3N) · Ubud Jungle Villa (3N)",
      shortDescription: "Private pool villas, jungle waterfalls, floating breakfast, and iconic Nusa Penida cliff viewpoints.",
      primaryDestination: destinationMap["bali"],
      destinations: [destinationMap["bali"]],
      theme: ["HONEYMOON", "LUXURY", "BEACH"],
      travelType: "CUSTOMIZABLE",
      audience: ["COUPLES"],
      nights: 6,
      days: 7,
      startingPrice: 38500,
      startingPriceCurrency: "INR",
      highlights: ["Private Pool Villa Stay", "Floating Breakfast Experience", "Nusa Penida Island Tour", "Tanah Lot Sunset Temple"],
      inclusions: ["3N Seminyak Villa + 3N Ubud Villa", "Private Chauffeur Car for 7 Days", "Daily Breakfast", "Speedboat to Nusa Penida"],
      exclusions: ["International Flights", "Bali Tourist Levy", "Personal expenses"],
      itinerary: [],
      seo: { title: "Bali Private Pool Villa Tour | Be My Traveller", metaDescription: "Exclusive Bali honeymoon with private pool villas and Nusa Penida." },
      faqs: [],
      status: "PUBLISHED",
      publishedAt: new Date(),
      averageRating: 4.9,
      reviewCount: 167,
      createdBy: adminId,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  for (const pkg of samplePackages) {
    await packagesCol.findOneAndUpdate(
      { slug: pkg.slug },
      { $set: pkg },
      { upsert: true }
    );
  }
  console.log(`✅ ${samplePackages.length} Tour Packages seeded.`);

  // ── 4. Seed Live Leads ──
  console.log("📋 Seeding Sample Leads...");
  const leadsCol = db.collection("leads");

  const sampleLeads = [
    {
      name: "Rahul Sharma",
      phone: "+91 8091638090",
      email: "rahul.sharma@example.com",
      destinations: ["Himachal Pradesh"],
      travelDates: { from: new Date("2026-10-15"), to: new Date("2026-10-22"), flexible: true },
      travellers: { adults: 2, children: 1, infants: 0 },
      budget: { min: 40000, max: 60000, currency: "INR" },
      specialRequirements: "Interested in: 6 Nights 7 Days Majestic Himachal & Rohtang Pass Tour",
      status: "NEW",
      source: "HOMEPAGE_WIDGET",
      createdAt: new Date(Date.now() - 1000 * 60 * 35), // 35 mins ago
      updatedAt: new Date(),
    },
    {
      name: "Priya & Rohit Mehta",
      phone: "+91 87654 32109",
      email: "priya.mehta@gmail.com",
      destinations: ["Kerala Backwaters"],
      travelDates: { from: new Date("2026-11-05"), to: new Date("2026-11-11"), flexible: false },
      travellers: { adults: 2, children: 0, infants: 0 },
      budget: { min: 50000, max: 70000, currency: "INR" },
      specialRequirements: "Honeymoon package with private luxury houseboat in Alleppey",
      status: "CONTACTED",
      source: "PACKAGE_PAGE",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4), // 4 hours ago
      updatedAt: new Date(),
    },
    {
      name: "Vikramaditya Rao",
      phone: "+91 76543 21098",
      email: "vikram.rao@company.com",
      destinations: ["Royal Rajasthan"],
      travelDates: { from: new Date("2026-12-20"), to: new Date("2026-12-27"), flexible: false },
      travellers: { adults: 6, children: 2, infants: 0 },
      budget: { min: 150000, max: 250000, currency: "INR" },
      specialRequirements: "Corporate group & family year-end trip covering Udaipur & Jaipur",
      status: "QUOTE_SENT",
      source: "CUSTOM_TRIP_BUILDER",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24), // 1 day ago
      updatedAt: new Date(),
    },
    {
      name: "Ananya Joshi",
      phone: "+91 65432 10987",
      email: "ananya.j@gmail.com",
      destinations: ["Bali Tropical Villas"],
      travelDates: { from: new Date("2026-10-01"), to: new Date("2026-10-08"), flexible: true },
      travellers: { adults: 2, children: 0, infants: 0 },
      budget: { min: 80000, max: 120000, currency: "INR" },
      specialRequirements: "Private pool villa in Ubud + Seminyak beach stay",
      status: "NEW",
      source: "HOMEPAGE_WIDGET",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2), // 2 hours ago
      updatedAt: new Date(),
    },
  ];

  for (const lead of sampleLeads) {
    await leadsCol.findOneAndUpdate(
      { email: lead.email, name: lead.name },
      { $set: lead },
      { upsert: true }
    );
  }
  console.log(`✅ ${sampleLeads.length} Sample Leads seeded.`);

  console.log("\n=======================================================");
  console.log("🎉 MASTER SEED COMPLETED SUCCESSFULLY!");
  console.log("=======================================================");
  console.log("🔑 ADMIN CREDENTIALS:");
  console.log(`   Username: Admin   (or admin@bemytraveller.com)`);
  console.log(`   Password: ${adminPassword}`);
  console.log(`   Login at: http://localhost:3000/admin/login`);
  console.log("=======================================================\n");

  await mongoose.disconnect();
}

seedMaster().catch((err) => {
  console.error("❌ Master Seed Failed:", err);
  process.exit(1);
});
